### PR TITLE
Circle android 2

### PR DESCRIPTION
**Pull request by johnthepink**
All working:

- [x] gagarin tests
- [x] android build
- [x] android hockey deploy
- [x] ios build
- [x] ios hockey deploy

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
very nice

**Comment by johnthepink** [comment]
@jbaxleyiii https://circleci.com/gh/NewSpring/newspring-app/520

**Comment by johnthepink** [comment]
and... confirmed builds made it to hockey

**Comment by jbaxleyiii** [comment]
@johnthepink you win

**Pull request merged**
