### PR TITLE
Dynamic nav

### PR DESCRIPTION
**Pull request by jbaxleyiii**
This brings support for dynamic nav and starting patterns for using redux.

### CODE REVIEW

**Comment by johnthepink** [comment]
@jbaxleyiii i got a couple errors when running this.

On loading the page:

```
Warning: Location "/" did not match any routes
```

and when clicking back:

```
Uncaught TypeError: action is not a function
```

**Comment by johnthepink** [comment]
i tried updating dependencies

**Comment by jbaxleyiii** [comment]
@johnthepink dang, I'll try to reproduce

**Comment by jbaxleyiii** [comment]
@johnthepink can reproduce. I'll work through some bugs :+1:

**Comment by jbaxleyiii** [comment]
@johnthepink can you give this another shot when you get a chance?

**Comment by johnthepink** [comment]
@jbaxleyiii looks good!

**Pull request merged**
