### PR TITLE
Fix Closed Items

### LINKED ISSUE #65: Don't show future stories
...do the same filtering as articles...etc

### PR DESCRIPTION
**Pull request by johnthepink**
I think the future stories we were seeing actually had a status of "closed". We shouldn't show data that is closed. So, this filters all our current data by whether or not it is closed. Because of this, it was also necessary to add status to the home feed collection.

Although, we could just not add an item to the home feed if it is closed? What do you think @jbaxleyiii? Is there any reason we would need closed items in the home feed?

This fixes #65

### CODE REVIEW

**Comment by johnthepink** [comment]
Or, we could even not sync an item over at all from EE if it is closed.

**Comment by jbaxleyiii** [comment]
@johnthepink I like the idea of never showing closed items. I would say keep syncing them because old syncs can become closed retroactively. Having them consistent in the store would be nice

**Comment by johnthepink** [comment]
@jbaxleyiii sounds good. So you'd be in favor of the changes currently? Or, syncing the data but not creating homeFeed items for them?

**Comment by jbaxleyiii** [comment]
@johnthepink I'm good with how it is now :+1: merging...

**Pull request merged**
